server:
    server.port=8089

spring:
#    jpa:
#        hibernate:
#            dll-auto: create-drop
#        show-sql: false
#        properties:
#            hibernate:
#                hbm2ddl:
#                    auto: update
    jpa:
        properties:
            hibernate:
#                dialect: org.hibernate.dialect.PostgreSQL10Dialect
                #log
                show_sql: false
#                temp:
#                    # without metadata from DB
#                    use_jdbc_metadata_defaults: false

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://db22.spmi.edu.ru:5432/university
        username: university_db
        password: "osiris"
#    flyway:
#        baseline-on-migrate: true
springdoc:
    show-actuator: true
    swagger-ui:
        enabled: true
        path: swagger-ui.html


jwt:
    header:
        Authorization
    secret:
        spmi
    time:
        expired:
            5000
        accept:
            300
    issuer:
        app