server:
    server.port=9000

spring:
    jpa:
        hibernate:
            dll-auto: create-drop
        show-sql: false
        properties:
            hibernate:
                hbm2ddl:
                    auto: update

    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
#    flyway:
#        baseline-on-migrate: true

jwt:
    header:
        Authorization
    secret:
        spmi
    time:
        expired:
            5000
        accept:
            300
    issuer:
        app